# Generated by Django 4.0.2 on 2022-06-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_servicodeteccaoface_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipoUser',
        ),
    ]
