# Generated by Django 3.2.4 on 2021-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20210625_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipoUser',
            field=models.CharField(blank=True, choices=[('Gerente', 'Habilita usuarios e cadastra layer, controlpoint e camera'), ('Habilita e desabilita agentes', 'Analista'), ('Segurança', 'Segurança')], max_length=150, verbose_name='Função'),
        ),
    ]
