# Generated by Django 3.2.4 on 2021-07-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo', max_length=8),
        ),
    ]
