# Generated by Django 3.2.4 on 2021-07-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipoUser',
            field=models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Analista', 'Analista'), ('Segurança', 'Segurança')], max_length=150, verbose_name='Função'),
        ),
    ]
