# Generated by Django 3.2.4 on 2021-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_layer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
    ]
