# Generated by Django 3.2.4 on 2021-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_detectedlicenseplate_img_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='roubo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='camera',
            name='direction',
            field=models.CharField(choices=[('in', 'Entrada do campus'), ('out', 'Saída do campus'), ('even', 'Lado par da via'), ('odd', 'Lado ímpar da via'), ('free', 'Movimento livre (domo)'), ('sidewalk', 'Câmera de calçada')], max_length=8),
        ),
    ]
