from server.packages.alerta_individuo import AlertaIndividuoSerializer
from server.packages.etiqueta_individuo import EtiquetaIndividuoSerializer
from server.packages.individuo import IndividuoSerializer
from server.packages.ocorrencia_face import OcorrenciaFaceSerializer
from server.packages.permissao_individuo import PermissaoIndividuoSerializer
from server.packages.servico_deteccao_face import ServicoDeteccaoFaceSerializer
from server.packages.tipo_servico import TipoServicoSerializer
from server.packages.user import UserSerializer
