# Generated by Django 3.2.4 on 2021-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alertveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, choices=[('Gerente', 'Habilita usuarios e cadastra layer, controlpoint e camera'), ('Analista', 'Habilita e desabilita agentes'), ('Segurança', 'Acessa informacoes salvas')], max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Usuario ativo'), ('Inativo', 'Usuario inativo')], max_length=8),
        ),
    ]
