# Generated by Django 3.2.4 on 2021-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20210707_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
        migrations.AddField(
            model_name='layer',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
    ]
