# Generated by Django 3.2.4 on 2021-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20210707_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8),
        ),
    ]
