# Generated by Django 3.2.4 on 2021-06-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210612_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=200)),
                ('ano', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='detectedlicenseplate',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitor.veiculo'),
        ),
    ]
