# Generated by Django 3.2.4 on 2021-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20210630_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Usuario ativo'), ('Inativo', 'Usuario inativo')], default='Inativo', max_length=8),
        ),
    ]
