# Generated by Django 3.2.4 on 2021-07-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20210702_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertveiculo',
            name='license_plate',
            field=models.CharField(max_length=7, verbose_name='Placa'),
        ),
        migrations.CreateModel(
            name='HistoricoAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=200)),
                ('obs', models.TextField(blank=True, max_length=400)),
                ('update_date', models.DateTimeField()),
                ('alertVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.alertveiculo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
