# Generated by Django 3.2.4 on 2021-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20210707_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedlicenseplate',
            name='img_filename',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
